email:
  host: test.com
  port: 2400
  ignore_tls: true
  secure: false
  require_tls: false
  user: test
  password: password
  default_from: test@from.com
  default_name: default_name
endpoints:
  - id: '123'
    receivers: [test@mail1.de, test2@mail2.de]
    data_type: blank
    subject: 'Alert from 123'
  - id: '456'
    receivers: [test456@mail1.de, test2@mail2.de]
    data_type: json
    subject: 'Alert from 456'
